name: Database Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Supabase CLI
        run: npm install -g supabase
      
      - name: Set up database URL
        run: echo "DATABASE_URL=${{ secrets.SUPABASE_DB_URL }}" >> $GITHUB_ENV
      
      - name: Create backup
        run: |
          mkdir -p backups
          pg_dump $DATABASE_URL > backups/backup-$(date +%Y%m%d).sql
      
      - name: Upload backup
        uses: actions/upload-artifact@v3
        with:
          name: db-backup-$(date +%Y%m%d)
          path: backups/
          retention-days: 30
